package main

import "fmt"

// Stat contains report counters
type Stat struct {
	DoNotModify int
	Skipped     int
	Added       int
}

// String returns stat as nice human string
func (s *Stat) String() string {
	return fmt.Sprintf("License propagation: %d added, %d skipped, %d autogenerated files",
		s.Added, s.Skipped, s.DoNotModify)
}

// NewStat returns new statistics report
func NewStat() *Stat {
	return &Stat{}
}
